name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          VITE_DATADOG_APPLICATION_ID: ${{ secrets.VITE_DATADOG_APPLICATION_ID }}
          VITE_DATADOG_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_CLIENT_TOKEN }}
          VITE_DATADOG_LOGS_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_LOGS_CLIENT_TOKEN }}

      # Add the Depcheck step here
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk  # Reset JAVA_HOME to match the Depcheck Docker image
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports'  # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist/
          
      - name: Upload Dependency Check Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensures write access to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we are on the main branch
          fetch-depth: 0  # Fetch full history to avoid detached HEAD issues

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist/

      - name: Download dependency check report artifact
        uses: actions/download-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

      - name: Commit and push Dependency Check Report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add Dependency Check report"
          branch: main
          file_pattern: reports/*
          commit_user_name: GitHub Actions  # Optional, sets commit author
          commit_user_email: actions@github.com  # Optional, sets commit email

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

