name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          VITE_DATADOG_APPLICATION_ID: ${{ secrets.VITE_DATADOG_APPLICATION_ID }}
          VITE_DATADOG_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_CLIENT_TOKEN }}
          VITE_DATADOG_LOGS_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_LOGS_CLIENT_TOKEN }}

      # Add the Depcheck step here
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk  # Reset JAVA_HOME to match the Depcheck Docker image
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports'  # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: dist/

      - name: Upload Dependency Check Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: dist/

      - name: Download the report artifact
        uses: actions/download-artifact@v4
        with:
          name: dependency-check-report
          path: reports/
    
      - name: Unzip the downloaded report artifact
        run: |
          mkdir -p reports
          unzip -o reports/dependency-check-report.zip -d reports/
      
      - name: View the report locally
        run: |
          echo "Report downloaded to the reports folder."
          ls reports

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
